#!/usr/bin/env sh

# Set good defaults to allow script to be run by hand
DOCKER_REPO=${DOCKER_REPO:-"efrecon/kubectl"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

GH_PROJECT=kubernetes/kubernetes

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

for tag in $(github_releases "$GH_PROJECT" | sort); do
  if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
    echo "============== Pushing ${DOCKER_REPO}:$tag"
    docker push "${DOCKER_REPO}:$tag"
  else
    echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
  fi
done
