#!/usr/bin/env sh

# Set good defaults to allow script to be run by hand. The two variables below
# will never be used when run from within the Docker hub.
DOCKER_REPO=${DOCKER_REPO:-"efrecon/vcluster"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

GH_API=https://api.github.com/
GH_PROJECT=loft-sh/vcluster

# rx for matching release versions of helm/vcluster
SEMVER_ALL='v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+\.[0-9]+)?'

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

for tag in $(github_releases --release "$SEMVER_ALL" "$GH_PROJECT" | sort); do
  if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
    echo "============== Pushing ${DOCKER_REPO}:$tag"
    docker push "${DOCKER_REPO}:$tag"
  else
    echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
  fi
done
