name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  kubectl:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd kubectl && ./hooks/build
      -
        name: Build Docker hub images
        env:
          DOCKER_REPO: docker.io/efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd kubectl && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd kubectl && ./hooks/push
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd kubectl && ./hooks/push
  helm:
    runs-on: ubuntu-latest
    needs: kubectl
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/build
      -
        name: Build Docker hub images
        env:
          DOCKER_REPO: docker.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/push
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/push
  vcluster:
    runs-on: ubuntu-latest
    needs:
      - kubectl
      - helm
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/vcluster
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd vcluster && ./hooks/build
      -
        name: Build Docker hub images
        env:
          DOCKER_REPO: docker.io/efrecon/vcluster
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd vcluster && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/vcluster
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd vcluster && ./hooks/push
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/vcluster
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd vcluster && ./hooks/push