name: ghcr

on:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build missing images
        env:
          DOCKER_REPO: ghcr.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/build
      -
        name: Push updated images
        env:
          DOCKER_REPO: ghcr.io/efrecon/helm
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd helm && ./hooks/push
