name: ghcr

on:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build missing images
        env:
          DOCKER_REPO: efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd kubectl && ./hooks/build
      -
        name: Push updated images
        env:
          DOCKER_REPO: efrecon/kubectl
          SOURCE_COMMIT: ${{ github.sha }}
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf %s\\n "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin ghcr.io \
            && cd kubectl \
            && ./hooks/push \
            && docker logout
